Undo one lint:fix change, because it breaks tsc
$ yarn test
yarn run v1.22.11
$ mocha --recursive "test/**/*.ts" --exit

TSError: ⨯ Unable to compile TypeScript:
test/chai/matchers/bigNumber.ts:78:55 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.
  Type 'string' is not assignable to type 'number | Date'.

78       checkAll(10, 9, (a, b) => expect(a).to.be.above(b));
                                                         ~
test/chai/matchers/bigNumber.ts:82:52 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

82       checkAll(10, 9, (a, b) => expect(a).to.be.gt(b));
                                                      ~
test/chai/matchers/bigNumber.ts:86:60 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

86       checkAll(10, 10, (a, b) => expect(a).not.to.be.above(b));
                                                              ~
test/chai/matchers/bigNumber.ts:87:60 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

87       checkAll(10, 11, (a, b) => expect(a).not.to.be.above(b));
                                                              ~
test/chai/matchers/bigNumber.ts:91:57 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

91       checkAll(10, 10, (a, b) => expect(a).not.to.be.gt(b));
                                                           ~
test/chai/matchers/bigNumber.ts:92:57 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

92       checkAll(10, 11, (a, b) => expect(a).not.to.be.gt(b));
                                                           ~
test/chai/matchers/bigNumber.ts:98:56 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

98       checkAll(10, 11, (a, b) => expect(a).to.be.below(b));
                                                          ~
test/chai/matchers/bigNumber.ts:102:53 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

102       checkAll(10, 11, (a, b) => expect(a).to.be.lt(b));
                                                        ~
test/chai/matchers/bigNumber.ts:106:60 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

106       checkAll(10, 10, (a, b) => expect(a).not.to.be.below(b));
                                                               ~
test/chai/matchers/bigNumber.ts:107:59 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

107       checkAll(10, 9, (a, b) => expect(a).not.to.be.below(b));
                                                              ~
test/chai/matchers/bigNumber.ts:111:57 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

111       checkAll(10, 10, (a, b) => expect(a).not.to.be.lt(b));
                                                            ~
test/chai/matchers/bigNumber.ts:112:56 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

112       checkAll(10, 9, (a, b) => expect(a).not.to.be.lt(b));
                                                           ~
test/chai/matchers/bigNumber.ts:118:59 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

118       checkAll(10, 10, (a, b) => expect(a).to.be.at.least(b));
                                                              ~
test/chai/matchers/bigNumber.ts:119:58 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

119       checkAll(10, 9, (a, b) => expect(a).to.be.at.least(b));
                                                             ~
test/chai/matchers/bigNumber.ts:123:54 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

123       checkAll(10, 10, (a, b) => expect(a).to.be.gte(b));
                                                         ~
test/chai/matchers/bigNumber.ts:124:53 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

124       checkAll(10, 9, (a, b) => expect(a).to.be.gte(b));
                                                        ~
test/chai/matchers/bigNumber.ts:128:63 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

128       checkAll(10, 11, (a, b) => expect(a).not.to.be.at.least(b));
                                                                  ~
test/chai/matchers/bigNumber.ts:132:58 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

132       checkAll(10, 11, (a, b) => expect(a).not.to.be.gte(b));
                                                             ~
test/chai/matchers/bigNumber.ts:138:58 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

138       checkAll(10, 10, (a, b) => expect(a).to.be.at.most(b));
                                                             ~
test/chai/matchers/bigNumber.ts:139:58 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

139       checkAll(10, 11, (a, b) => expect(a).to.be.at.most(b));
                                                             ~
test/chai/matchers/bigNumber.ts:143:54 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

143       checkAll(10, 10, (a, b) => expect(a).to.be.lte(b));
                                                         ~
test/chai/matchers/bigNumber.ts:144:54 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

144       checkAll(10, 11, (a, b) => expect(a).to.be.lte(b));
                                                         ~
test/chai/matchers/bigNumber.ts:148:61 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

148       checkAll(10, 9, (a, b) => expect(a).not.to.be.at.most(b));
                                                                ~
test/chai/matchers/bigNumber.ts:152:57 - error TS2345: Argument of type 'string | number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number | Date'.

152       checkAll(10, 9, (a, b) => expect(a).not.to.be.lte(b));
                                                            ~
test/chai/matchers/bigNumber.ts:215:33 - error TS2345: Argument of type 'number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number'.
  Type 'bigint' is not assignable to type 'number'.

215         expect(a).to.be.closeTo(b, c)
                                    ~
test/chai/matchers/bigNumber.ts:221:37 - error TS2345: Argument of type 'number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number'.

221         expect(a).to.not.be.closeTo(b, c)
                                        ~
test/chai/matchers/bigNumber.ts:228:35 - error TS2345: Argument of type 'number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number'.

228           expect(a).to.be.closeTo(b, c)
                                      ~
test/chai/matchers/bigNumber.ts:233:39 - error TS2345: Argument of type 'number | bigint | BN | BigNumber | BigNumber' is not assignable to parameter of type 'number'.

233           expect(a).not.to.be.closeTo(b, c)
                                          ~

    at createTSError (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gene/dev/nomiclabs/hardhat/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at requireOrImport (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/esm-utils.js:28:26)
    at Mocha.loadFilesAsync (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/mocha.js:386:19)
    at singleRun (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/cli/run-helpers.js:149:15)
    at exports.runMocha (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/cli/run-helpers.js:186:11)
    at Object.exports.handler (/home/gene/dev/nomiclabs/hardhat/node_modules/mocha/lib/cli/run.js:319:11)
    at /home/gene/dev/nomiclabs/hardhat/node_modules/yargs/lib/command.js:241:49
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.